# -------------------------------
# 基本信息
# -------------------------------
title: Your Awesome Blog
author: Chenyi Zhu
email: lanae_z@outlook.com/241098060@smail.nju.edu.cn
description: > 
  Write an awesome description for your site here. 
  It will appear in meta tags for SEO.
show_excerpts: true

# -------------------------------
# 主题配置
# -------------------------------
# 使用 remote_theme 方式，最简单，兼容 GitHub Pages
remote_theme: samarsault/plainwhite-jekyll
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# 如果你希望用本地主题 gem，则改成：
# theme: plainwhite
# 并在 Gemfile 里确保 gem "plainwhite" 已安装

# plainwhite 特定配置
plainwhite:
  name: Chenyi Zhu
  tagline: Student of NJU
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: true
  portfolio_image: "assets/portrait3.png"
  html_lang: "en"
  condensed_mobile:
    - page
    - post
  social_links:
    twitter: your-twitter
    github: https://github.com/lanae-z
    linkedIn: www.linkedin.com/in/晨奕-朱-1985a93b3

# -------------------------------
# Sass 配置
# -------------------------------
sass:
  sass_dir: _sass

# -------------------------------
# 页面头部链接（可选）
# -------------------------------
#header_pages:
# - about.md

# -------------------------------
# 构建设置
# -------------------------------
# 如果使用本地主题 gem，这里保持 theme: plainwhite
# 如果使用 remote_theme，则不需要 theme
#theme: plainwhite
